/*
 * MODULE: biotransformation
 * Reads the Biotransformation sheet from Template_open.ods and produces:
 *   - ACTIVITY.tsv  (ChEMBL deposition format)
 *
 * CIDX is resolved by matching Common_Name against:
 *   1. The Chemicals sheet in the template (Chemical_identifier column)
 *   2. COMPOUND_RECORD.tsv from GENERATE_CHEMICALS (COMPOUND_NAME → CIDX),
 *      which takes priority when CIDXs were auto-generated by the workflow.
 *
 * AIDX is resolved by matching ASSAY_Identifier against:
 *   ASSAY_MAPPING.tsv from GENERATE_ASSAY (USER_AIDX → AIDX),
 *   which converts the user's short key (e.g. 'assay1') to the
 *   pipeline-generated ChEMBL AIDX.  This file is an intermediate only
 *   and is not published to the output directory.
 *
 * ACTIVITY_COMMENT is auto-built by concatenating the free-text comment
 * with MIX-MB extension fields (reaction type, metabolite m/z, retention
 * time, annotation, and annotation level).
 */

process GENERATE_ACTIVITY {
    tag "biotransformation → ACTIVITY"
    publishDir "${params.outdir}", mode: 'copy'
    conda "${projectDir}/envs/py_env.yml"

    input:
    path ods
    val  ridx
    path compound_record   // COMPOUND_RECORD.tsv from GENERATE_CHEMICALS
    path assay_mapping     // ASSAY_MAPPING.tsv   from GENERATE_ASSAY (intermediate)

    output:
    path "ACTIVITY.tsv", emit: activity

    script:
    def strict_flag = params.strict ? "--strict" : ""
    """
    python ${projectDir}/bin/biotransformation.py \\
        --input     "${ods}" \\
        --ridx      "${ridx}" \\
        --compounds "${compound_record}" \\
        --assays    "${assay_mapping}" \\
        --outdir    . \\
        ${strict_flag}
    """
}
