name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'bin/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read workflow version
        id: version
        run: echo "version=$(cat versions/framework.txt)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zmahnoor/bioxend:latest
            zmahnoor/bioxend:${{ steps.version.outputs.version }}
